<h1>Customer Q&A:</h1>
<?php $questions = $this->fetchQuestions(); ?>
<div class="reviews-container">
    <?php foreach ($questions as $question): ?>
        <div class="row-question">
            <p><?php
                $userName = $question->getData('user_name');
                $text = $question->getData('question');
                $adminName = $question->getData('firstname') . ' ' . $question->getData('lastname');
                $answer = $question->getData('answer');
                ?>
            <div id="qa_name"><?= $userName?></div>
            <div id="qa_text"><?= $text ?></div></p>
            <?php if ($answer) : ?>
                <div class="row-answer"><p>
                    <div id="qa_name"><?= $adminName ?></div>
                    <div id="qa_text"><?= $answer ?></div></div>
                <?php endif; ?>
            </p></div><br>
    <?php endforeach; ?>
</div>