<?php $questions = $this->fetchQuestions(); ?>
<div class="reviews-container">
    <?php foreach ($questions as $question): ?>
        <div class="row-question">
            <p><?php
                $email = $question->getData('email');
                $text = $question->getData('text');
                $adminName = $question->getData('firstname') . ' ' . $question->getData('lastname');
                $answer = $question->getData('answer');
                echo $email . ': ' . $text;
                ?></p>
            <p><?php
                if ($answer) {
                    echo $adminName . ': ' . $answer;
                }
                ?>
            </p></div><br>
    <?php endforeach; ?>
</div>
