<?php $questions = $this->fetchQuestions();
?>
<div class="reviews-container">
    <?php foreach ($questions as $question) {
        ?><div class="row-question"><h2>
                <?php $questionID = $question->getData('question_id');
                echo $question->getText();
                $answer = $this->fetchAnswer($questionID);
                Mage::log($answer,null,'myLog.log');
                ?>
            </h2></div>
<?php } ?>
</div>
