<?php

$_menu = $this->getMenuItems();
$_count = count($_menu);
$i = 0;
?>
<?php if($_menu): ?>
<nav id="nav">
    <ol class="nav-primary">
        <?php foreach ($_menu as $_menuItem): ?>
        <?php $additionalClass = ++$i == 1 ? ' first' : (($i == $_count) ? ' last' : '') ?>
        <?php $dynamicBlock = $this->getDynamicBlock($_menuItem, $i) ?>
        <?php if ($dynamicBlock) { $additionalClass .= ' parent'; } ?>
        <li class="level0 nav-<?php echo $i . $additionalClass ?>">
            <a
                    title="<?php echo $this->escapeHtml($_menuItem->getTitle()) ?>"
                    href="<?php echo $this->escapeUrl($this->getItemUrl($_menuItem)) ?>"
                    class="level0<?php echo $dynamicBlock ? ' has-children' : '' ?>"
                    ><span><?php echo $this->escapeHtml($_menuItem->getLabel()) ?></span>
            </a>
            <?php echo $dynamicBlock ?>
        </li>
        <?php endforeach ?>
    </ol>
</nav>
<?php endif ?>

